---
- hosts: webservers
  become: true
  tasks:
    - name : User removal
      user:
        name: sverma
        state: absent
        remove: yes
      register: userremoval
    
    - debug: msg="user sverma has been removed from {{ ansible_hostname }}"
      when: userremoval.changed

    - debug: var=userremoval

